## Importing Liabraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

## Loading the Dataset

In [4]:
data = pd.read_csv(r'C:\Users\ADMIN\Desktop\Jupyter folder/Downloads/Melbourne_housing_FULL.csv')
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [5]:
data.shape

(34857, 21)

In [6]:
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [7]:
data.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [8]:
data.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [9]:
coln = ['Suburb','Rooms','Type','Method','SellerG','Car','Bathroom','Bedroom2','Landsize','Distance','CouncilArea','BuildingArea','Regionname',
       'Propertycount','Price']
data = data[coln]
data

,Suburb,Rooms,Type,Method,SellerG,Car,Bathroom,Bedroom2,Landsize,Distance,CouncilArea,BuildingArea,Regionname,Propertycount,Price
0,Abbotsford,2,h,SS,Jellis,1.0,1.0,2.0,126.0,2.5,Yarra City Council,NaN,Northern Metropolitan,4019.0,NaN
1,Abbotsford,2,h,S,Biggin,1.0,1.0,2.0,202.0,2.5,Yarra City Council,NaN,Northern Metropolitan,4019.0,1480000.0
2,Abbotsford,2,h,S,Biggin,0.0,1.0,2.0,156.0,2.5,Yarra City Council,79.0,Northern Metropolitan,4019.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,1.0,2.0,3.0,0.0,2.5,Yarra City Council,NaN,Northern Metropolitan,4019.0,NaN
4,Abbotsford,3,h,SP,Biggin,0.0,2.0,3.0,134.0,2.5,Yarra City Council,150.0,Northern Metropolitan,4019.0,1465000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,PI,Jas,3.0,1.0,4.0,593.0,6.3,Maribyrnong City Council,NaN,Western Metropolitan,6543.0,1480000.0
34853,Yarraville,2,h,SP,Sweeney,1.0,2.0,2.0,98.0,6.3,Maribyrnong City Council,104.0,Western Metropolitan,6543.0,888000.0
34854,Yarraville,2,t,S,Jas,2.0,1.0,2.0,220.0,6.3,Maribyrnong City Council,120.0,Western Metropolitan,6543.0,705000.0
34855,Yarraville,3,h,SP,hockingstuart,NaN,NaN,NaN,NaN,6.3,Maribyrnong City Council,NaN,Western Metropolitan,6543.0,1140000.0
34856,Yarraville,2,h,PI,RW,0.0,1.0,2.0,250.0,6.3,Maribyrnong City Council,103.0,Western Metropolitan,6543.0,1020000.0

In [10]:
data.shape

(34857, 15)

## Checking of Null values

In [11]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Car               8728
Bathroom          8226
Bedroom2          8217
Landsize         11810
Distance             1
CouncilArea          3
BuildingArea     21115
Regionname           3
Propertycount        3
Price             7610
dtype: int64

## Handling the Missing values

In [28]:
ctfz = ['Propertycount','Distance','Car','Bathroom','Bedroom2']
data[ctfz] = data[ctfz].fillna(0)

data['Landsize'] = data['Landsize'].fillna(data.Landsize.mean())
data['BuildingArea'] = data['BuildingArea'].fillna(data.BuildingArea.mean())

In [29]:
data.dropna(inplace=True)
data

,Rooms,Car,Bathroom,Bedroom2,Landsize,Distance,BuildingArea,Propertycount,Price,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1.0,1.0,2.0,202.000000,2.5,160.2564,4019.0,1480000.0,False,...,False,True,False,False,True,False,False,False,False,False
2,2,0.0,1.0,2.0,156.000000,2.5,79.0000,4019.0,1035000.0,False,...,False,True,False,False,True,False,False,False,False,False
4,3,0.0,2.0,3.0,134.000000,2.5,150.0000,4019.0,1465000.0,False,...,False,True,False,False,True,False,False,False,False,False
5,3,1.0,2.0,3.0,94.000000,2.5,160.2564,4019.0,850000.0,False,...,False,True,False,False,True,False,False,False,False,False
6,4,2.0,1.0,3.0,120.000000,2.5,142.0000,4019.0,1600000.0,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,3.0,1.0,4.0,593.000000,6.3,160.2564,6543.0,1480000.0,False,...,False,False,False,False,False,False,False,False,True,False
34853,2,1.0,2.0,2.0,98.000000,6.3,104.0000,6543.0,888000.0,False,...,False,False,False,False,False,False,False,False,True,False
34854,2,2.0,1.0,2.0,220.000000,6.3,120.0000,6543.0,705000.0,False,...,False,False,False,False,False,False,False,False,True,False
34855,3,0.0,0.0,0.0,593.598993,6.3,160.2564,6543.0,1140000.0,False,...,False,False,False,False,False,False,False,False,True,False
34856,2,0.0,1.0,2.0,250.000000,6.3,103.0000,6543.0,1020000.0,False,...,False,False,False,False,False,False,False,False,True,False

In [14]:
data.shape

(27244, 15)

## Let's One hot encode the categorical Features

In [15]:
data = pd.get_dummies(data, drop_first=True)
data.head()

,Rooms,Car,Bathroom,Bedroom2,Landsize,Distance,BuildingArea,Propertycount,Price,Suburb_Aberfeldie,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1.0,1.0,2.0,202.0,2.5,160.2564,4019.0,1480000.0,False,...,False,True,False,False,True,False,False,False,False,False
2,2,0.0,1.0,2.0,156.0,2.5,79.0000,4019.0,1035000.0,False,...,False,True,False,False,True,False,False,False,False,False
4,3,0.0,2.0,3.0,134.0,2.5,150.0000,4019.0,1465000.0,False,...,False,True,False,False,True,False,False,False,False,False
5,3,1.0,2.0,3.0,94.0,2.5,160.2564,4019.0,850000.0,False,...,False,True,False,False,True,False,False,False,False,False
6,4,2.0,1.0,3.0,120.0,2.5,142.0000,4019.0,1600000.0,False,...,False,True,False,False,True,False,False,False,False,False

## Split into two

In [16]:
x = data.drop('Price',axis=1)
y = data['Price']
x

,Rooms,Car,Bathroom,Bedroom2,Landsize,Distance,BuildingArea,Propertycount,Suburb_Aberfeldie,Suburb_Airport West,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
1,2,1.0,1.0,2.0,202.000000,2.5,160.2564,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
2,2,0.0,1.0,2.0,156.000000,2.5,79.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
4,3,0.0,2.0,3.0,134.000000,2.5,150.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
5,3,1.0,2.0,3.0,94.000000,2.5,160.2564,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
6,4,2.0,1.0,3.0,120.000000,2.5,142.0000,4019.0,False,False,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,3.0,1.0,4.0,593.000000,6.3,160.2564,6543.0,False,False,...,False,False,False,False,False,False,False,False,True,False
34853,2,1.0,2.0,2.0,98.000000,6.3,104.0000,6543.0,False,False,...,False,False,False,False,False,False,False,False,True,False
34854,2,2.0,1.0,2.0,220.000000,6.3,120.0000,6543.0,False,False,...,False,False,False,False,False,False,False,False,True,False
34855,3,0.0,0.0,0.0,593.598993,6.3,160.2564,6543.0,False,False,...,False,False,False,False,False,False,False,False,True,False
34856,2,0.0,1.0,2.0,250.000000,6.3,103.0000,6543.0,False,False,...,False,False,False,False,False,False,False,False,True,False

In [17]:
y

1        1480000.0
2        1035000.0
4        1465000.0
5         850000.0
6        1600000.0
           ...
34852    1480000.0
34853     888000.0
34854     705000.0
34855    1140000.0
34856    1020000.0
Name: Price, Length: 27244, dtype: float64

## Train and Test

In [18]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=2)

In [19]:
from sklearn.linear_model import LinearRegression
rg = LinearRegression().fit(X_train, y_train)

In [20]:
rg.score(X_test, y_test)

0.13853683161571617

In [21]:
rg.score(X_train, y_train)

0.6827792395792722

Here the Training Score is 68% and the Testing Score is 13 %.

<h3 style='color:blue', align='center'> L1 Regularization </h3>

## Using Lasso(L1) regularization model

In [33]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50 ,max_iter=100, tol=0.1)
lasso_reg.fit(X_train, y_train)

C:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.329e+15, tolerance: 7.963e+14
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=50, max_iter=100, tol=0.1)

In [23]:
lasso_reg.score(X_test, y_test)

0.6637595089746127

In [24]:
lasso_reg.score(X_train, y_train)

0.6767356676358025

## Using Ridge (L2) Reguralization model

In [25]:
from sklearn import linear_model
ridge_reg = linear_model.Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [26]:
ridge_reg.score(X_test, y_test)

0.6670848945194956

In [27]:
ridge_reg.score(X_train, y_train)

0.6622376739684328